/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AccountAggregatorRouteImport } from './routes/account-aggregator'
import { Route as AssistanceChoiceRouteImport } from './routes/assistance-choice'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CompareOffersRouteImport } from './routes/compare-offers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DigitalLendingDisclosuresRouteImport } from './routes/digital-lending-disclosures'
import { Route as EmiCalculatorRouteImport } from './routes/emi-calculator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as ForBorrowersRouteImport } from './routes/for-borrowers'
import { Route as ForLendersRouteImport } from './routes/for-lenders'
import { Route as GrievanceRedressalRouteImport } from './routes/grievance-redressal'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as KeyFactStatementRouteImport } from './routes/key-fact-statement'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as PartnerEnquiryRouteImport } from './routes/partner-enquiry'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ErrorsIndexRouteImport } from './routes/errors.index'
import { Route as Errors401RouteImport } from './routes/errors.401'
import { Route as Errors403RouteImport } from './routes/errors.403'
import { Route as Errors410RouteImport } from './routes/errors.410'
import { Route as Errors429RouteImport } from './routes/errors.429'
import { Route as Errors500RouteImport } from './routes/errors.500'
import { Route as Errors503RouteImport } from './routes/errors.503'
import { Route as ErrorsDeactivatedRouteImport } from './routes/errors.deactivated'
import { Route as ErrorsMaintenanceRouteImport } from './routes/errors.maintenance'
import { Route as ErrorsNoResultsRouteImport } from './routes/errors.no-results'
import { Route as ErrorsOfflineRouteImport } from './routes/errors.offline'
import { Route as ErrorsScriptFailureRouteImport } from './routes/errors.script-failure'
import { Route as ErrorsSecurityRouteImport } from './routes/errors.security'
import { Route as ErrorsSuspendedRouteImport } from './routes/errors.suspended'
import { Route as ErrorsUnsupportedBrowserRouteImport } from './routes/errors.unsupported-browser'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as LoansBusinessRouteImport } from './routes/loans.business'
import { Route as LoansHomeRouteImport } from './routes/loans.home'
import { Route as LoansMortgageRouteImport } from './routes/loans.mortgage'
import { Route as LoansPersonalRouteImport } from './routes/loans.personal'
import { Route as LoansSachetRouteImport } from './routes/loans.sachet'
import { Route as PrototypeIndexRouteImport } from './routes/prototype.index'
import { Route as PrototypeMotionRouteImport } from './routes/prototype.motion'
import { Route as TrustCenterIndexRouteImport } from './routes/trust-center.index'
import { Route as TrustCenterPrivacyAndDataRouteImport } from './routes/trust-center.privacy-and-data'
import { Route as TrustCenterRbiComplianceRouteImport } from './routes/trust-center.rbi-compliance'
import { Route as TrustCenterSecurityRouteImport } from './routes/trust-center.security'
import { Route as TrustCenterSnvTrustScoreRouteImport } from './routes/trust-center.snv-trust-score'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminAgentsRouteImport } from './routes/app.admin.agents'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminBorrowersRouteImport } from './routes/app.admin.borrowers'
import { Route as AppAdminCmsRouteImport } from './routes/app.admin.cms'
import { Route as AppAdminConsentRouteImport } from './routes/app.admin.consent'
import { Route as AppAdminFraudRouteImport } from './routes/app.admin.fraud'
import { Route as AppAdminLendersRouteImport } from './routes/app.admin.lenders'
import { Route as AppAdminLoansRouteImport } from './routes/app.admin.loans'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminTrustScoreRouteImport } from './routes/app.admin.trust-score'
import { Route as AppAgentIndexRouteImport } from './routes/app.agent.index'
import { Route as AppAgentAnalyticsRouteImport } from './routes/app.agent.analytics'
import { Route as AppAgentCommissionsRouteImport } from './routes/app.agent.commissions'
import { Route as AppAgentFilesRouteImport } from './routes/app.agent.files'
import { Route as AppAgentLeadsRouteImport } from './routes/app.agent.leads'
import { Route as AppAgentNotificationsRouteImport } from './routes/app.agent.notifications'
import { Route as AppAgentProfileRouteImport } from './routes/app.agent.profile'
import { Route as AppAgentResourcesRouteImport } from './routes/app.agent.resources'
import { Route as AppAgentStartRouteImport } from './routes/app.agent.start'
import { Route as AppAgentSupportRouteImport } from './routes/app.agent.support'
import { Route as AppAgentTrainingRouteImport } from './routes/app.agent.training'
import { Route as AppBorrowerIndexRouteImport } from './routes/app.borrower.index'
import { Route as AppBorrowerAgentsRouteImport } from './routes/app.borrower.agents'
import { Route as AppBorrowerApplicationRouteImport } from './routes/app.borrower.application'
import { Route as AppBorrowerApplicationsRouteImport } from './routes/app.borrower.applications'
import { Route as AppBorrowerApplyRouteImport } from './routes/app.borrower.apply'
import { Route as AppBorrowerDocumentsRouteImport } from './routes/app.borrower.documents'
import { Route as AppBorrowerLoansRouteImport } from './routes/app.borrower.loans'
import { Route as AppBorrowerMessagesRouteImport } from './routes/app.borrower.messages'
import { Route as AppBorrowerNotificationsRouteImport } from './routes/app.borrower.notifications'
import { Route as AppBorrowerOffersRouteImport } from './routes/app.borrower.offers'
import { Route as AppBorrowerPaymentsRouteImport } from './routes/app.borrower.payments'
import { Route as AppBorrowerProfileRouteImport } from './routes/app.borrower.profile'
import { Route as AppBorrowerScoresRouteImport } from './routes/app.borrower.scores'
import { Route as AppBorrowerSupportRouteImport } from './routes/app.borrower.support'
import { Route as AppLenderIndexRouteImport } from './routes/app.lender.index'
import { Route as AppLenderApiStatusRouteImport } from './routes/app.lender.api-status'
import { Route as AppLenderAuditRouteImport } from './routes/app.lender.audit'
import { Route as AppLenderBillingRouteImport } from './routes/app.lender.billing'
import { Route as AppLenderPortfolioRouteImport } from './routes/app.lender.portfolio'
import { Route as AppLenderReviewsRouteImport } from './routes/app.lender.reviews'
import { Route as AppLenderRiskRouteImport } from './routes/app.lender.risk'
import { Route as AppLenderSettingsRouteImport } from './routes/app.lender.settings'
import { Route as AppLenderTeamRouteImport } from './routes/app.lender.team'
import { Route as AppLenderWorkbenchRouteImport } from './routes/app.lender.workbench'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAggregatorRoute = AccountAggregatorRouteImport.update({
  id: '/account-aggregator',
  path: '/account-aggregator',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistanceChoiceRoute = AssistanceChoiceRouteImport.update({
  id: '/assistance-choice',
  path: '/assistance-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareOffersRoute = CompareOffersRouteImport.update({
  id: '/compare-offers',
  path: '/compare-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalLendingDisclosuresRoute =
  DigitalLendingDisclosuresRouteImport.update({
    id: '/digital-lending-disclosures',
    path: '/digital-lending-disclosures',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmiCalculatorRoute = EmiCalculatorRouteImport.update({
  id: '/emi-calculator',
  path: '/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBorrowersRoute = ForBorrowersRouteImport.update({
  id: '/for-borrowers',
  path: '/for-borrowers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLendersRoute = ForLendersRouteImport.update({
  id: '/for-lenders',
  path: '/for-lenders',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRedressalRoute = GrievanceRedressalRouteImport.update({
  id: '/grievance-redressal',
  path: '/grievance-redressal',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyFactStatementRoute = KeyFactStatementRouteImport.update({
  id: '/key-fact-statement',
  path: '/key-fact-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerEnquiryRoute = PartnerEnquiryRouteImport.update({
  id: '/partner-enquiry',
  path: '/partner-enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsIndexRoute = ErrorsIndexRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors401Route = Errors401RouteImport.update({
  id: '/errors/401',
  path: '/errors/401',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors410Route = Errors410RouteImport.update({
  id: '/errors/410',
  path: '/errors/410',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors429Route = Errors429RouteImport.update({
  id: '/errors/429',
  path: '/errors/429',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors503Route = Errors503RouteImport.update({
  id: '/errors/503',
  path: '/errors/503',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsDeactivatedRoute = ErrorsDeactivatedRouteImport.update({
  id: '/errors/deactivated',
  path: '/errors/deactivated',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsMaintenanceRoute = ErrorsMaintenanceRouteImport.update({
  id: '/errors/maintenance',
  path: '/errors/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsNoResultsRoute = ErrorsNoResultsRouteImport.update({
  id: '/errors/no-results',
  path: '/errors/no-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsOfflineRoute = ErrorsOfflineRouteImport.update({
  id: '/errors/offline',
  path: '/errors/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsScriptFailureRoute = ErrorsScriptFailureRouteImport.update({
  id: '/errors/script-failure',
  path: '/errors/script-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsSecurityRoute = ErrorsSecurityRouteImport.update({
  id: '/errors/security',
  path: '/errors/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsSuspendedRoute = ErrorsSuspendedRouteImport.update({
  id: '/errors/suspended',
  path: '/errors/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsUnsupportedBrowserRoute =
  ErrorsUnsupportedBrowserRouteImport.update({
    id: '/errors/unsupported-browser',
    path: '/errors/unsupported-browser',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansBusinessRoute = LoansBusinessRouteImport.update({
  id: '/loans/business',
  path: '/loans/business',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansHomeRoute = LoansHomeRouteImport.update({
  id: '/loans/home',
  path: '/loans/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansMortgageRoute = LoansMortgageRouteImport.update({
  id: '/loans/mortgage',
  path: '/loans/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansPersonalRoute = LoansPersonalRouteImport.update({
  id: '/loans/personal',
  path: '/loans/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansSachetRoute = LoansSachetRouteImport.update({
  id: '/loans/sachet',
  path: '/loans/sachet',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeIndexRoute = PrototypeIndexRouteImport.update({
  id: '/prototype/',
  path: '/prototype/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMotionRoute = PrototypeMotionRouteImport.update({
  id: '/prototype/motion',
  path: '/prototype/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterIndexRoute = TrustCenterIndexRouteImport.update({
  id: '/trust-center/',
  path: '/trust-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterPrivacyAndDataRoute =
  TrustCenterPrivacyAndDataRouteImport.update({
    id: '/trust-center/privacy-and-data',
    path: '/trust-center/privacy-and-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustCenterRbiComplianceRoute =
  TrustCenterRbiComplianceRouteImport.update({
    id: '/trust-center/rbi-compliance',
    path: '/trust-center/rbi-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustCenterSecurityRoute = TrustCenterSecurityRouteImport.update({
  id: '/trust-center/security',
  path: '/trust-center/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterSnvTrustScoreRoute =
  TrustCenterSnvTrustScoreRouteImport.update({
    id: '/trust-center/snv-trust-score',
    path: '/trust-center/snv-trust-score',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/app/admin/',
  path: '/app/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAgentsRoute = AppAdminAgentsRouteImport.update({
  id: '/app/admin/agents',
  path: '/app/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/app/admin/audit',
  path: '/app/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminBorrowersRoute = AppAdminBorrowersRouteImport.update({
  id: '/app/admin/borrowers',
  path: '/app/admin/borrowers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminCmsRoute = AppAdminCmsRouteImport.update({
  id: '/app/admin/cms',
  path: '/app/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminConsentRoute = AppAdminConsentRouteImport.update({
  id: '/app/admin/consent',
  path: '/app/admin/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminFraudRoute = AppAdminFraudRouteImport.update({
  id: '/app/admin/fraud',
  path: '/app/admin/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminLendersRoute = AppAdminLendersRouteImport.update({
  id: '/app/admin/lenders',
  path: '/app/admin/lenders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminLoansRoute = AppAdminLoansRouteImport.update({
  id: '/app/admin/loans',
  path: '/app/admin/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/app/admin/reports',
  path: '/app/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/app/admin/settings',
  path: '/app/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/app/admin/system',
  path: '/app/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminTrustScoreRoute = AppAdminTrustScoreRouteImport.update({
  id: '/app/admin/trust-score',
  path: '/app/admin/trust-score',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentIndexRoute = AppAgentIndexRouteImport.update({
  id: '/app/agent/',
  path: '/app/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentAnalyticsRoute = AppAgentAnalyticsRouteImport.update({
  id: '/app/agent/analytics',
  path: '/app/agent/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentCommissionsRoute = AppAgentCommissionsRouteImport.update({
  id: '/app/agent/commissions',
  path: '/app/agent/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentFilesRoute = AppAgentFilesRouteImport.update({
  id: '/app/agent/files',
  path: '/app/agent/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentLeadsRoute = AppAgentLeadsRouteImport.update({
  id: '/app/agent/leads',
  path: '/app/agent/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentNotificationsRoute = AppAgentNotificationsRouteImport.update({
  id: '/app/agent/notifications',
  path: '/app/agent/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentProfileRoute = AppAgentProfileRouteImport.update({
  id: '/app/agent/profile',
  path: '/app/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentResourcesRoute = AppAgentResourcesRouteImport.update({
  id: '/app/agent/resources',
  path: '/app/agent/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentStartRoute = AppAgentStartRouteImport.update({
  id: '/app/agent/start',
  path: '/app/agent/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentSupportRoute = AppAgentSupportRouteImport.update({
  id: '/app/agent/support',
  path: '/app/agent/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentTrainingRoute = AppAgentTrainingRouteImport.update({
  id: '/app/agent/training',
  path: '/app/agent/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerIndexRoute = AppBorrowerIndexRouteImport.update({
  id: '/app/borrower/',
  path: '/app/borrower/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerAgentsRoute = AppBorrowerAgentsRouteImport.update({
  id: '/app/borrower/agents',
  path: '/app/borrower/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerApplicationRoute = AppBorrowerApplicationRouteImport.update({
  id: '/app/borrower/application',
  path: '/app/borrower/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerApplicationsRoute = AppBorrowerApplicationsRouteImport.update({
  id: '/app/borrower/applications',
  path: '/app/borrower/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerApplyRoute = AppBorrowerApplyRouteImport.update({
  id: '/app/borrower/apply',
  path: '/app/borrower/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerDocumentsRoute = AppBorrowerDocumentsRouteImport.update({
  id: '/app/borrower/documents',
  path: '/app/borrower/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerLoansRoute = AppBorrowerLoansRouteImport.update({
  id: '/app/borrower/loans',
  path: '/app/borrower/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerMessagesRoute = AppBorrowerMessagesRouteImport.update({
  id: '/app/borrower/messages',
  path: '/app/borrower/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerNotificationsRoute =
  AppBorrowerNotificationsRouteImport.update({
    id: '/app/borrower/notifications',
    path: '/app/borrower/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppBorrowerOffersRoute = AppBorrowerOffersRouteImport.update({
  id: '/app/borrower/offers',
  path: '/app/borrower/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerPaymentsRoute = AppBorrowerPaymentsRouteImport.update({
  id: '/app/borrower/payments',
  path: '/app/borrower/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerProfileRoute = AppBorrowerProfileRouteImport.update({
  id: '/app/borrower/profile',
  path: '/app/borrower/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerScoresRoute = AppBorrowerScoresRouteImport.update({
  id: '/app/borrower/scores',
  path: '/app/borrower/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBorrowerSupportRoute = AppBorrowerSupportRouteImport.update({
  id: '/app/borrower/support',
  path: '/app/borrower/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderIndexRoute = AppLenderIndexRouteImport.update({
  id: '/app/lender/',
  path: '/app/lender/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderApiStatusRoute = AppLenderApiStatusRouteImport.update({
  id: '/app/lender/api-status',
  path: '/app/lender/api-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderAuditRoute = AppLenderAuditRouteImport.update({
  id: '/app/lender/audit',
  path: '/app/lender/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderBillingRoute = AppLenderBillingRouteImport.update({
  id: '/app/lender/billing',
  path: '/app/lender/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderPortfolioRoute = AppLenderPortfolioRouteImport.update({
  id: '/app/lender/portfolio',
  path: '/app/lender/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderReviewsRoute = AppLenderReviewsRouteImport.update({
  id: '/app/lender/reviews',
  path: '/app/lender/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderRiskRoute = AppLenderRiskRouteImport.update({
  id: '/app/lender/risk',
  path: '/app/lender/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderSettingsRoute = AppLenderSettingsRouteImport.update({
  id: '/app/lender/settings',
  path: '/app/lender/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderTeamRoute = AppLenderTeamRouteImport.update({
  id: '/app/lender/team',
  path: '/app/lender/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLenderWorkbenchRoute = AppLenderWorkbenchRouteImport.update({
  id: '/app/lender/workbench',
  path: '/app/lender/workbench',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account-aggregator': typeof AccountAggregatorRoute
  '/assistance-choice': typeof AssistanceChoiceRoute
  '/careers': typeof CareersRoute
  '/compare-offers': typeof CompareOffersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/digital-lending-disclosures': typeof DigitalLendingDisclosuresRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faq': typeof FaqRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-borrowers': typeof ForBorrowersRoute
  '/for-lenders': typeof ForLendersRoute
  '/grievance-redressal': typeof GrievanceRedressalRoute
  '/help-center': typeof HelpCenterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/key-fact-statement': typeof KeyFactStatementRoute
  '/mcp': typeof McpRoute
  '/motion': typeof MotionRoute
  '/partner-enquiry': typeof PartnerEnquiryRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system-status': typeof SystemStatusRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/410': typeof Errors410Route
  '/errors/429': typeof Errors429Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/errors/deactivated': typeof ErrorsDeactivatedRoute
  '/errors/maintenance': typeof ErrorsMaintenanceRoute
  '/errors/no-results': typeof ErrorsNoResultsRoute
  '/errors/offline': typeof ErrorsOfflineRoute
  '/errors/script-failure': typeof ErrorsScriptFailureRoute
  '/errors/security': typeof ErrorsSecurityRoute
  '/errors/suspended': typeof ErrorsSuspendedRoute
  '/errors/unsupported-browser': typeof ErrorsUnsupportedBrowserRoute
  '/loans/business': typeof LoansBusinessRoute
  '/loans/home': typeof LoansHomeRoute
  '/loans/mortgage': typeof LoansMortgageRoute
  '/loans/personal': typeof LoansPersonalRoute
  '/loans/sachet': typeof LoansSachetRoute
  '/prototype/motion': typeof PrototypeMotionRoute
  '/trust-center/privacy-and-data': typeof TrustCenterPrivacyAndDataRoute
  '/trust-center/rbi-compliance': typeof TrustCenterRbiComplianceRoute
  '/trust-center/security': typeof TrustCenterSecurityRoute
  '/trust-center/snv-trust-score': typeof TrustCenterSnvTrustScoreRoute
  '/blog/': typeof BlogIndexRoute
  '/errors/': typeof ErrorsIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/prototype/': typeof PrototypeIndexRoute
  '/trust-center/': typeof TrustCenterIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin/agents': typeof AppAdminAgentsRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/borrowers': typeof AppAdminBorrowersRoute
  '/app/admin/cms': typeof AppAdminCmsRoute
  '/app/admin/consent': typeof AppAdminConsentRoute
  '/app/admin/fraud': typeof AppAdminFraudRoute
  '/app/admin/lenders': typeof AppAdminLendersRoute
  '/app/admin/loans': typeof AppAdminLoansRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/trust-score': typeof AppAdminTrustScoreRoute
  '/app/agent/analytics': typeof AppAgentAnalyticsRoute
  '/app/agent/commissions': typeof AppAgentCommissionsRoute
  '/app/agent/files': typeof AppAgentFilesRoute
  '/app/agent/leads': typeof AppAgentLeadsRoute
  '/app/agent/notifications': typeof AppAgentNotificationsRoute
  '/app/agent/profile': typeof AppAgentProfileRoute
  '/app/agent/resources': typeof AppAgentResourcesRoute
  '/app/agent/start': typeof AppAgentStartRoute
  '/app/agent/support': typeof AppAgentSupportRoute
  '/app/agent/training': typeof AppAgentTrainingRoute
  '/app/borrower/agents': typeof AppBorrowerAgentsRoute
  '/app/borrower/application': typeof AppBorrowerApplicationRoute
  '/app/borrower/applications': typeof AppBorrowerApplicationsRoute
  '/app/borrower/apply': typeof AppBorrowerApplyRoute
  '/app/borrower/documents': typeof AppBorrowerDocumentsRoute
  '/app/borrower/loans': typeof AppBorrowerLoansRoute
  '/app/borrower/messages': typeof AppBorrowerMessagesRoute
  '/app/borrower/notifications': typeof AppBorrowerNotificationsRoute
  '/app/borrower/offers': typeof AppBorrowerOffersRoute
  '/app/borrower/payments': typeof AppBorrowerPaymentsRoute
  '/app/borrower/profile': typeof AppBorrowerProfileRoute
  '/app/borrower/scores': typeof AppBorrowerScoresRoute
  '/app/borrower/support': typeof AppBorrowerSupportRoute
  '/app/lender/api-status': typeof AppLenderApiStatusRoute
  '/app/lender/audit': typeof AppLenderAuditRoute
  '/app/lender/billing': typeof AppLenderBillingRoute
  '/app/lender/portfolio': typeof AppLenderPortfolioRoute
  '/app/lender/reviews': typeof AppLenderReviewsRoute
  '/app/lender/risk': typeof AppLenderRiskRoute
  '/app/lender/settings': typeof AppLenderSettingsRoute
  '/app/lender/team': typeof AppLenderTeamRoute
  '/app/lender/workbench': typeof AppLenderWorkbenchRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/agent/': typeof AppAgentIndexRoute
  '/app/borrower/': typeof AppBorrowerIndexRoute
  '/app/lender/': typeof AppLenderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account-aggregator': typeof AccountAggregatorRoute
  '/assistance-choice': typeof AssistanceChoiceRoute
  '/careers': typeof CareersRoute
  '/compare-offers': typeof CompareOffersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/digital-lending-disclosures': typeof DigitalLendingDisclosuresRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faq': typeof FaqRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-borrowers': typeof ForBorrowersRoute
  '/for-lenders': typeof ForLendersRoute
  '/grievance-redressal': typeof GrievanceRedressalRoute
  '/help-center': typeof HelpCenterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/key-fact-statement': typeof KeyFactStatementRoute
  '/mcp': typeof McpRoute
  '/motion': typeof MotionRoute
  '/partner-enquiry': typeof PartnerEnquiryRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system-status': typeof SystemStatusRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/410': typeof Errors410Route
  '/errors/429': typeof Errors429Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/errors/deactivated': typeof ErrorsDeactivatedRoute
  '/errors/maintenance': typeof ErrorsMaintenanceRoute
  '/errors/no-results': typeof ErrorsNoResultsRoute
  '/errors/offline': typeof ErrorsOfflineRoute
  '/errors/script-failure': typeof ErrorsScriptFailureRoute
  '/errors/security': typeof ErrorsSecurityRoute
  '/errors/suspended': typeof ErrorsSuspendedRoute
  '/errors/unsupported-browser': typeof ErrorsUnsupportedBrowserRoute
  '/loans/business': typeof LoansBusinessRoute
  '/loans/home': typeof LoansHomeRoute
  '/loans/mortgage': typeof LoansMortgageRoute
  '/loans/personal': typeof LoansPersonalRoute
  '/loans/sachet': typeof LoansSachetRoute
  '/prototype/motion': typeof PrototypeMotionRoute
  '/trust-center/privacy-and-data': typeof TrustCenterPrivacyAndDataRoute
  '/trust-center/rbi-compliance': typeof TrustCenterRbiComplianceRoute
  '/trust-center/security': typeof TrustCenterSecurityRoute
  '/trust-center/snv-trust-score': typeof TrustCenterSnvTrustScoreRoute
  '/blog': typeof BlogIndexRoute
  '/errors': typeof ErrorsIndexRoute
  '/loans': typeof LoansIndexRoute
  '/prototype': typeof PrototypeIndexRoute
  '/trust-center': typeof TrustCenterIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin/agents': typeof AppAdminAgentsRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/borrowers': typeof AppAdminBorrowersRoute
  '/app/admin/cms': typeof AppAdminCmsRoute
  '/app/admin/consent': typeof AppAdminConsentRoute
  '/app/admin/fraud': typeof AppAdminFraudRoute
  '/app/admin/lenders': typeof AppAdminLendersRoute
  '/app/admin/loans': typeof AppAdminLoansRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/trust-score': typeof AppAdminTrustScoreRoute
  '/app/agent/analytics': typeof AppAgentAnalyticsRoute
  '/app/agent/commissions': typeof AppAgentCommissionsRoute
  '/app/agent/files': typeof AppAgentFilesRoute
  '/app/agent/leads': typeof AppAgentLeadsRoute
  '/app/agent/notifications': typeof AppAgentNotificationsRoute
  '/app/agent/profile': typeof AppAgentProfileRoute
  '/app/agent/resources': typeof AppAgentResourcesRoute
  '/app/agent/start': typeof AppAgentStartRoute
  '/app/agent/support': typeof AppAgentSupportRoute
  '/app/agent/training': typeof AppAgentTrainingRoute
  '/app/borrower/agents': typeof AppBorrowerAgentsRoute
  '/app/borrower/application': typeof AppBorrowerApplicationRoute
  '/app/borrower/applications': typeof AppBorrowerApplicationsRoute
  '/app/borrower/apply': typeof AppBorrowerApplyRoute
  '/app/borrower/documents': typeof AppBorrowerDocumentsRoute
  '/app/borrower/loans': typeof AppBorrowerLoansRoute
  '/app/borrower/messages': typeof AppBorrowerMessagesRoute
  '/app/borrower/notifications': typeof AppBorrowerNotificationsRoute
  '/app/borrower/offers': typeof AppBorrowerOffersRoute
  '/app/borrower/payments': typeof AppBorrowerPaymentsRoute
  '/app/borrower/profile': typeof AppBorrowerProfileRoute
  '/app/borrower/scores': typeof AppBorrowerScoresRoute
  '/app/borrower/support': typeof AppBorrowerSupportRoute
  '/app/lender/api-status': typeof AppLenderApiStatusRoute
  '/app/lender/audit': typeof AppLenderAuditRoute
  '/app/lender/billing': typeof AppLenderBillingRoute
  '/app/lender/portfolio': typeof AppLenderPortfolioRoute
  '/app/lender/reviews': typeof AppLenderReviewsRoute
  '/app/lender/risk': typeof AppLenderRiskRoute
  '/app/lender/settings': typeof AppLenderSettingsRoute
  '/app/lender/team': typeof AppLenderTeamRoute
  '/app/lender/workbench': typeof AppLenderWorkbenchRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/agent': typeof AppAgentIndexRoute
  '/app/borrower': typeof AppBorrowerIndexRoute
  '/app/lender': typeof AppLenderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account-aggregator': typeof AccountAggregatorRoute
  '/assistance-choice': typeof AssistanceChoiceRoute
  '/careers': typeof CareersRoute
  '/compare-offers': typeof CompareOffersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/digital-lending-disclosures': typeof DigitalLendingDisclosuresRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faq': typeof FaqRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-borrowers': typeof ForBorrowersRoute
  '/for-lenders': typeof ForLendersRoute
  '/grievance-redressal': typeof GrievanceRedressalRoute
  '/help-center': typeof HelpCenterRoute
  '/how-it-works': typeof HowItWorksRoute
  '/key-fact-statement': typeof KeyFactStatementRoute
  '/mcp': typeof McpRoute
  '/motion': typeof MotionRoute
  '/partner-enquiry': typeof PartnerEnquiryRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/system-status': typeof SystemStatusRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/410': typeof Errors410Route
  '/errors/429': typeof Errors429Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/errors/deactivated': typeof ErrorsDeactivatedRoute
  '/errors/maintenance': typeof ErrorsMaintenanceRoute
  '/errors/no-results': typeof ErrorsNoResultsRoute
  '/errors/offline': typeof ErrorsOfflineRoute
  '/errors/script-failure': typeof ErrorsScriptFailureRoute
  '/errors/security': typeof ErrorsSecurityRoute
  '/errors/suspended': typeof ErrorsSuspendedRoute
  '/errors/unsupported-browser': typeof ErrorsUnsupportedBrowserRoute
  '/loans/business': typeof LoansBusinessRoute
  '/loans/home': typeof LoansHomeRoute
  '/loans/mortgage': typeof LoansMortgageRoute
  '/loans/personal': typeof LoansPersonalRoute
  '/loans/sachet': typeof LoansSachetRoute
  '/prototype/motion': typeof PrototypeMotionRoute
  '/trust-center/privacy-and-data': typeof TrustCenterPrivacyAndDataRoute
  '/trust-center/rbi-compliance': typeof TrustCenterRbiComplianceRoute
  '/trust-center/security': typeof TrustCenterSecurityRoute
  '/trust-center/snv-trust-score': typeof TrustCenterSnvTrustScoreRoute
  '/blog/': typeof BlogIndexRoute
  '/errors/': typeof ErrorsIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/prototype/': typeof PrototypeIndexRoute
  '/trust-center/': typeof TrustCenterIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/admin/agents': typeof AppAdminAgentsRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/borrowers': typeof AppAdminBorrowersRoute
  '/app/admin/cms': typeof AppAdminCmsRoute
  '/app/admin/consent': typeof AppAdminConsentRoute
  '/app/admin/fraud': typeof AppAdminFraudRoute
  '/app/admin/lenders': typeof AppAdminLendersRoute
  '/app/admin/loans': typeof AppAdminLoansRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/trust-score': typeof AppAdminTrustScoreRoute
  '/app/agent/analytics': typeof AppAgentAnalyticsRoute
  '/app/agent/commissions': typeof AppAgentCommissionsRoute
  '/app/agent/files': typeof AppAgentFilesRoute
  '/app/agent/leads': typeof AppAgentLeadsRoute
  '/app/agent/notifications': typeof AppAgentNotificationsRoute
  '/app/agent/profile': typeof AppAgentProfileRoute
  '/app/agent/resources': typeof AppAgentResourcesRoute
  '/app/agent/start': typeof AppAgentStartRoute
  '/app/agent/support': typeof AppAgentSupportRoute
  '/app/agent/training': typeof AppAgentTrainingRoute
  '/app/borrower/agents': typeof AppBorrowerAgentsRoute
  '/app/borrower/application': typeof AppBorrowerApplicationRoute
  '/app/borrower/applications': typeof AppBorrowerApplicationsRoute
  '/app/borrower/apply': typeof AppBorrowerApplyRoute
  '/app/borrower/documents': typeof AppBorrowerDocumentsRoute
  '/app/borrower/loans': typeof AppBorrowerLoansRoute
  '/app/borrower/messages': typeof AppBorrowerMessagesRoute
  '/app/borrower/notifications': typeof AppBorrowerNotificationsRoute
  '/app/borrower/offers': typeof AppBorrowerOffersRoute
  '/app/borrower/payments': typeof AppBorrowerPaymentsRoute
  '/app/borrower/profile': typeof AppBorrowerProfileRoute
  '/app/borrower/scores': typeof AppBorrowerScoresRoute
  '/app/borrower/support': typeof AppBorrowerSupportRoute
  '/app/lender/api-status': typeof AppLenderApiStatusRoute
  '/app/lender/audit': typeof AppLenderAuditRoute
  '/app/lender/billing': typeof AppLenderBillingRoute
  '/app/lender/portfolio': typeof AppLenderPortfolioRoute
  '/app/lender/reviews': typeof AppLenderReviewsRoute
  '/app/lender/risk': typeof AppLenderRiskRoute
  '/app/lender/settings': typeof AppLenderSettingsRoute
  '/app/lender/team': typeof AppLenderTeamRoute
  '/app/lender/workbench': typeof AppLenderWorkbenchRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/agent/': typeof AppAgentIndexRoute
  '/app/borrower/': typeof AppBorrowerIndexRoute
  '/app/lender/': typeof AppLenderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/accessibility'
    | '/account-aggregator'
    | '/assistance-choice'
    | '/careers'
    | '/compare-offers'
    | '/contact'
    | '/cookie-policy'
    | '/digital-lending-disclosures'
    | '/emi-calculator'
    | '/faq'
    | '/for-agents'
    | '/for-borrowers'
    | '/for-lenders'
    | '/grievance-redressal'
    | '/help-center'
    | '/how-it-works'
    | '/key-fact-statement'
    | '/mcp'
    | '/motion'
    | '/partner-enquiry'
    | '/press'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/system-status'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/signin'
    | '/auth/signup'
    | '/blog/$slug'
    | '/errors/401'
    | '/errors/403'
    | '/errors/410'
    | '/errors/429'
    | '/errors/500'
    | '/errors/503'
    | '/errors/deactivated'
    | '/errors/maintenance'
    | '/errors/no-results'
    | '/errors/offline'
    | '/errors/script-failure'
    | '/errors/security'
    | '/errors/suspended'
    | '/errors/unsupported-browser'
    | '/loans/business'
    | '/loans/home'
    | '/loans/mortgage'
    | '/loans/personal'
    | '/loans/sachet'
    | '/prototype/motion'
    | '/trust-center/privacy-and-data'
    | '/trust-center/rbi-compliance'
    | '/trust-center/security'
    | '/trust-center/snv-trust-score'
    | '/blog/'
    | '/errors/'
    | '/loans/'
    | '/prototype/'
    | '/trust-center/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin/agents'
    | '/app/admin/audit'
    | '/app/admin/borrowers'
    | '/app/admin/cms'
    | '/app/admin/consent'
    | '/app/admin/fraud'
    | '/app/admin/lenders'
    | '/app/admin/loans'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/system'
    | '/app/admin/trust-score'
    | '/app/agent/analytics'
    | '/app/agent/commissions'
    | '/app/agent/files'
    | '/app/agent/leads'
    | '/app/agent/notifications'
    | '/app/agent/profile'
    | '/app/agent/resources'
    | '/app/agent/start'
    | '/app/agent/support'
    | '/app/agent/training'
    | '/app/borrower/agents'
    | '/app/borrower/application'
    | '/app/borrower/applications'
    | '/app/borrower/apply'
    | '/app/borrower/documents'
    | '/app/borrower/loans'
    | '/app/borrower/messages'
    | '/app/borrower/notifications'
    | '/app/borrower/offers'
    | '/app/borrower/payments'
    | '/app/borrower/profile'
    | '/app/borrower/scores'
    | '/app/borrower/support'
    | '/app/lender/api-status'
    | '/app/lender/audit'
    | '/app/lender/billing'
    | '/app/lender/portfolio'
    | '/app/lender/reviews'
    | '/app/lender/risk'
    | '/app/lender/settings'
    | '/app/lender/team'
    | '/app/lender/workbench'
    | '/app/admin/'
    | '/app/agent/'
    | '/app/borrower/'
    | '/app/lender/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/accessibility'
    | '/account-aggregator'
    | '/assistance-choice'
    | '/careers'
    | '/compare-offers'
    | '/contact'
    | '/cookie-policy'
    | '/digital-lending-disclosures'
    | '/emi-calculator'
    | '/faq'
    | '/for-agents'
    | '/for-borrowers'
    | '/for-lenders'
    | '/grievance-redressal'
    | '/help-center'
    | '/how-it-works'
    | '/key-fact-statement'
    | '/mcp'
    | '/motion'
    | '/partner-enquiry'
    | '/press'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/system-status'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/signin'
    | '/auth/signup'
    | '/blog/$slug'
    | '/errors/401'
    | '/errors/403'
    | '/errors/410'
    | '/errors/429'
    | '/errors/500'
    | '/errors/503'
    | '/errors/deactivated'
    | '/errors/maintenance'
    | '/errors/no-results'
    | '/errors/offline'
    | '/errors/script-failure'
    | '/errors/security'
    | '/errors/suspended'
    | '/errors/unsupported-browser'
    | '/loans/business'
    | '/loans/home'
    | '/loans/mortgage'
    | '/loans/personal'
    | '/loans/sachet'
    | '/prototype/motion'
    | '/trust-center/privacy-and-data'
    | '/trust-center/rbi-compliance'
    | '/trust-center/security'
    | '/trust-center/snv-trust-score'
    | '/blog'
    | '/errors'
    | '/loans'
    | '/prototype'
    | '/trust-center'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin/agents'
    | '/app/admin/audit'
    | '/app/admin/borrowers'
    | '/app/admin/cms'
    | '/app/admin/consent'
    | '/app/admin/fraud'
    | '/app/admin/lenders'
    | '/app/admin/loans'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/system'
    | '/app/admin/trust-score'
    | '/app/agent/analytics'
    | '/app/agent/commissions'
    | '/app/agent/files'
    | '/app/agent/leads'
    | '/app/agent/notifications'
    | '/app/agent/profile'
    | '/app/agent/resources'
    | '/app/agent/start'
    | '/app/agent/support'
    | '/app/agent/training'
    | '/app/borrower/agents'
    | '/app/borrower/application'
    | '/app/borrower/applications'
    | '/app/borrower/apply'
    | '/app/borrower/documents'
    | '/app/borrower/loans'
    | '/app/borrower/messages'
    | '/app/borrower/notifications'
    | '/app/borrower/offers'
    | '/app/borrower/payments'
    | '/app/borrower/profile'
    | '/app/borrower/scores'
    | '/app/borrower/support'
    | '/app/lender/api-status'
    | '/app/lender/audit'
    | '/app/lender/billing'
    | '/app/lender/portfolio'
    | '/app/lender/reviews'
    | '/app/lender/risk'
    | '/app/lender/settings'
    | '/app/lender/team'
    | '/app/lender/workbench'
    | '/app/admin'
    | '/app/agent'
    | '/app/borrower'
    | '/app/lender'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/accessibility'
    | '/account-aggregator'
    | '/assistance-choice'
    | '/careers'
    | '/compare-offers'
    | '/contact'
    | '/cookie-policy'
    | '/digital-lending-disclosures'
    | '/emi-calculator'
    | '/faq'
    | '/for-agents'
    | '/for-borrowers'
    | '/for-lenders'
    | '/grievance-redressal'
    | '/help-center'
    | '/how-it-works'
    | '/key-fact-statement'
    | '/mcp'
    | '/motion'
    | '/partner-enquiry'
    | '/press'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/system-status'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/signin'
    | '/auth/signup'
    | '/blog/$slug'
    | '/errors/401'
    | '/errors/403'
    | '/errors/410'
    | '/errors/429'
    | '/errors/500'
    | '/errors/503'
    | '/errors/deactivated'
    | '/errors/maintenance'
    | '/errors/no-results'
    | '/errors/offline'
    | '/errors/script-failure'
    | '/errors/security'
    | '/errors/suspended'
    | '/errors/unsupported-browser'
    | '/loans/business'
    | '/loans/home'
    | '/loans/mortgage'
    | '/loans/personal'
    | '/loans/sachet'
    | '/prototype/motion'
    | '/trust-center/privacy-and-data'
    | '/trust-center/rbi-compliance'
    | '/trust-center/security'
    | '/trust-center/snv-trust-score'
    | '/blog/'
    | '/errors/'
    | '/loans/'
    | '/prototype/'
    | '/trust-center/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/admin/agents'
    | '/app/admin/audit'
    | '/app/admin/borrowers'
    | '/app/admin/cms'
    | '/app/admin/consent'
    | '/app/admin/fraud'
    | '/app/admin/lenders'
    | '/app/admin/loans'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/system'
    | '/app/admin/trust-score'
    | '/app/agent/analytics'
    | '/app/agent/commissions'
    | '/app/agent/files'
    | '/app/agent/leads'
    | '/app/agent/notifications'
    | '/app/agent/profile'
    | '/app/agent/resources'
    | '/app/agent/start'
    | '/app/agent/support'
    | '/app/agent/training'
    | '/app/borrower/agents'
    | '/app/borrower/application'
    | '/app/borrower/applications'
    | '/app/borrower/apply'
    | '/app/borrower/documents'
    | '/app/borrower/loans'
    | '/app/borrower/messages'
    | '/app/borrower/notifications'
    | '/app/borrower/offers'
    | '/app/borrower/payments'
    | '/app/borrower/profile'
    | '/app/borrower/scores'
    | '/app/borrower/support'
    | '/app/lender/api-status'
    | '/app/lender/audit'
    | '/app/lender/billing'
    | '/app/lender/portfolio'
    | '/app/lender/reviews'
    | '/app/lender/risk'
    | '/app/lender/settings'
    | '/app/lender/team'
    | '/app/lender/workbench'
    | '/app/admin/'
    | '/app/agent/'
    | '/app/borrower/'
    | '/app/lender/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountAggregatorRoute: typeof AccountAggregatorRoute
  AssistanceChoiceRoute: typeof AssistanceChoiceRoute
  CareersRoute: typeof CareersRoute
  CompareOffersRoute: typeof CompareOffersRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DigitalLendingDisclosuresRoute: typeof DigitalLendingDisclosuresRoute
  EmiCalculatorRoute: typeof EmiCalculatorRoute
  FaqRoute: typeof FaqRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForBorrowersRoute: typeof ForBorrowersRoute
  ForLendersRoute: typeof ForLendersRoute
  GrievanceRedressalRoute: typeof GrievanceRedressalRoute
  HelpCenterRoute: typeof HelpCenterRoute
  HowItWorksRoute: typeof HowItWorksRoute
  KeyFactStatementRoute: typeof KeyFactStatementRoute
  McpRoute: typeof McpRoute
  MotionRoute: typeof MotionRoute
  PartnerEnquiryRoute: typeof PartnerEnquiryRoute
  PressRoute: typeof PressRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemStatusRoute: typeof SystemStatusRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  Errors401Route: typeof Errors401Route
  Errors403Route: typeof Errors403Route
  Errors410Route: typeof Errors410Route
  Errors429Route: typeof Errors429Route
  Errors500Route: typeof Errors500Route
  Errors503Route: typeof Errors503Route
  ErrorsDeactivatedRoute: typeof ErrorsDeactivatedRoute
  ErrorsMaintenanceRoute: typeof ErrorsMaintenanceRoute
  ErrorsNoResultsRoute: typeof ErrorsNoResultsRoute
  ErrorsOfflineRoute: typeof ErrorsOfflineRoute
  ErrorsScriptFailureRoute: typeof ErrorsScriptFailureRoute
  ErrorsSecurityRoute: typeof ErrorsSecurityRoute
  ErrorsSuspendedRoute: typeof ErrorsSuspendedRoute
  ErrorsUnsupportedBrowserRoute: typeof ErrorsUnsupportedBrowserRoute
  LoansBusinessRoute: typeof LoansBusinessRoute
  LoansHomeRoute: typeof LoansHomeRoute
  LoansMortgageRoute: typeof LoansMortgageRoute
  LoansPersonalRoute: typeof LoansPersonalRoute
  LoansSachetRoute: typeof LoansSachetRoute
  PrototypeMotionRoute: typeof PrototypeMotionRoute
  TrustCenterPrivacyAndDataRoute: typeof TrustCenterPrivacyAndDataRoute
  TrustCenterRbiComplianceRoute: typeof TrustCenterRbiComplianceRoute
  TrustCenterSecurityRoute: typeof TrustCenterSecurityRoute
  TrustCenterSnvTrustScoreRoute: typeof TrustCenterSnvTrustScoreRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ErrorsIndexRoute: typeof ErrorsIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
  PrototypeIndexRoute: typeof PrototypeIndexRoute
  TrustCenterIndexRoute: typeof TrustCenterIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AppAdminAgentsRoute: typeof AppAdminAgentsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBorrowersRoute: typeof AppAdminBorrowersRoute
  AppAdminCmsRoute: typeof AppAdminCmsRoute
  AppAdminConsentRoute: typeof AppAdminConsentRoute
  AppAdminFraudRoute: typeof AppAdminFraudRoute
  AppAdminLendersRoute: typeof AppAdminLendersRoute
  AppAdminLoansRoute: typeof AppAdminLoansRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminTrustScoreRoute: typeof AppAdminTrustScoreRoute
  AppAgentAnalyticsRoute: typeof AppAgentAnalyticsRoute
  AppAgentCommissionsRoute: typeof AppAgentCommissionsRoute
  AppAgentFilesRoute: typeof AppAgentFilesRoute
  AppAgentLeadsRoute: typeof AppAgentLeadsRoute
  AppAgentNotificationsRoute: typeof AppAgentNotificationsRoute
  AppAgentProfileRoute: typeof AppAgentProfileRoute
  AppAgentResourcesRoute: typeof AppAgentResourcesRoute
  AppAgentStartRoute: typeof AppAgentStartRoute
  AppAgentSupportRoute: typeof AppAgentSupportRoute
  AppAgentTrainingRoute: typeof AppAgentTrainingRoute
  AppBorrowerAgentsRoute: typeof AppBorrowerAgentsRoute
  AppBorrowerApplicationRoute: typeof AppBorrowerApplicationRoute
  AppBorrowerApplicationsRoute: typeof AppBorrowerApplicationsRoute
  AppBorrowerApplyRoute: typeof AppBorrowerApplyRoute
  AppBorrowerDocumentsRoute: typeof AppBorrowerDocumentsRoute
  AppBorrowerLoansRoute: typeof AppBorrowerLoansRoute
  AppBorrowerMessagesRoute: typeof AppBorrowerMessagesRoute
  AppBorrowerNotificationsRoute: typeof AppBorrowerNotificationsRoute
  AppBorrowerOffersRoute: typeof AppBorrowerOffersRoute
  AppBorrowerPaymentsRoute: typeof AppBorrowerPaymentsRoute
  AppBorrowerProfileRoute: typeof AppBorrowerProfileRoute
  AppBorrowerScoresRoute: typeof AppBorrowerScoresRoute
  AppBorrowerSupportRoute: typeof AppBorrowerSupportRoute
  AppLenderApiStatusRoute: typeof AppLenderApiStatusRoute
  AppLenderAuditRoute: typeof AppLenderAuditRoute
  AppLenderBillingRoute: typeof AppLenderBillingRoute
  AppLenderPortfolioRoute: typeof AppLenderPortfolioRoute
  AppLenderReviewsRoute: typeof AppLenderReviewsRoute
  AppLenderRiskRoute: typeof AppLenderRiskRoute
  AppLenderSettingsRoute: typeof AppLenderSettingsRoute
  AppLenderTeamRoute: typeof AppLenderTeamRoute
  AppLenderWorkbenchRoute: typeof AppLenderWorkbenchRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAgentIndexRoute: typeof AppAgentIndexRoute
  AppBorrowerIndexRoute: typeof AppBorrowerIndexRoute
  AppLenderIndexRoute: typeof AppLenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-aggregator': {
      id: '/account-aggregator'
      path: '/account-aggregator'
      fullPath: '/account-aggregator'
      preLoaderRoute: typeof AccountAggregatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistance-choice': {
      id: '/assistance-choice'
      path: '/assistance-choice'
      fullPath: '/assistance-choice'
      preLoaderRoute: typeof AssistanceChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-offers': {
      id: '/compare-offers'
      path: '/compare-offers'
      fullPath: '/compare-offers'
      preLoaderRoute: typeof CompareOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-lending-disclosures': {
      id: '/digital-lending-disclosures'
      path: '/digital-lending-disclosures'
      fullPath: '/digital-lending-disclosures'
      preLoaderRoute: typeof DigitalLendingDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi-calculator': {
      id: '/emi-calculator'
      path: '/emi-calculator'
      fullPath: '/emi-calculator'
      preLoaderRoute: typeof EmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-borrowers': {
      id: '/for-borrowers'
      path: '/for-borrowers'
      fullPath: '/for-borrowers'
      preLoaderRoute: typeof ForBorrowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-lenders': {
      id: '/for-lenders'
      path: '/for-lenders'
      fullPath: '/for-lenders'
      preLoaderRoute: typeof ForLendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance-redressal': {
      id: '/grievance-redressal'
      path: '/grievance-redressal'
      fullPath: '/grievance-redressal'
      preLoaderRoute: typeof GrievanceRedressalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-fact-statement': {
      id: '/key-fact-statement'
      path: '/key-fact-statement'
      fullPath: '/key-fact-statement'
      preLoaderRoute: typeof KeyFactStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-enquiry': {
      id: '/partner-enquiry'
      path: '/partner-enquiry'
      fullPath: '/partner-enquiry'
      preLoaderRoute: typeof PartnerEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/': {
      id: '/errors/'
      path: '/errors'
      fullPath: '/errors/'
      preLoaderRoute: typeof ErrorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/401': {
      id: '/errors/401'
      path: '/errors/401'
      fullPath: '/errors/401'
      preLoaderRoute: typeof Errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/410': {
      id: '/errors/410'
      path: '/errors/410'
      fullPath: '/errors/410'
      preLoaderRoute: typeof Errors410RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/429': {
      id: '/errors/429'
      path: '/errors/429'
      fullPath: '/errors/429'
      preLoaderRoute: typeof Errors429RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/503': {
      id: '/errors/503'
      path: '/errors/503'
      fullPath: '/errors/503'
      preLoaderRoute: typeof Errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/deactivated': {
      id: '/errors/deactivated'
      path: '/errors/deactivated'
      fullPath: '/errors/deactivated'
      preLoaderRoute: typeof ErrorsDeactivatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/maintenance': {
      id: '/errors/maintenance'
      path: '/errors/maintenance'
      fullPath: '/errors/maintenance'
      preLoaderRoute: typeof ErrorsMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/no-results': {
      id: '/errors/no-results'
      path: '/errors/no-results'
      fullPath: '/errors/no-results'
      preLoaderRoute: typeof ErrorsNoResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/offline': {
      id: '/errors/offline'
      path: '/errors/offline'
      fullPath: '/errors/offline'
      preLoaderRoute: typeof ErrorsOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/script-failure': {
      id: '/errors/script-failure'
      path: '/errors/script-failure'
      fullPath: '/errors/script-failure'
      preLoaderRoute: typeof ErrorsScriptFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/security': {
      id: '/errors/security'
      path: '/errors/security'
      fullPath: '/errors/security'
      preLoaderRoute: typeof ErrorsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/suspended': {
      id: '/errors/suspended'
      path: '/errors/suspended'
      fullPath: '/errors/suspended'
      preLoaderRoute: typeof ErrorsSuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/unsupported-browser': {
      id: '/errors/unsupported-browser'
      path: '/errors/unsupported-browser'
      fullPath: '/errors/unsupported-browser'
      preLoaderRoute: typeof ErrorsUnsupportedBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/business': {
      id: '/loans/business'
      path: '/loans/business'
      fullPath: '/loans/business'
      preLoaderRoute: typeof LoansBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/home': {
      id: '/loans/home'
      path: '/loans/home'
      fullPath: '/loans/home'
      preLoaderRoute: typeof LoansHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/mortgage': {
      id: '/loans/mortgage'
      path: '/loans/mortgage'
      fullPath: '/loans/mortgage'
      preLoaderRoute: typeof LoansMortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/personal': {
      id: '/loans/personal'
      path: '/loans/personal'
      fullPath: '/loans/personal'
      preLoaderRoute: typeof LoansPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/sachet': {
      id: '/loans/sachet'
      path: '/loans/sachet'
      fullPath: '/loans/sachet'
      preLoaderRoute: typeof LoansSachetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/': {
      id: '/prototype/'
      path: '/prototype'
      fullPath: '/prototype/'
      preLoaderRoute: typeof PrototypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/motion': {
      id: '/prototype/motion'
      path: '/prototype/motion'
      fullPath: '/prototype/motion'
      preLoaderRoute: typeof PrototypeMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center/': {
      id: '/trust-center/'
      path: '/trust-center'
      fullPath: '/trust-center/'
      preLoaderRoute: typeof TrustCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center/privacy-and-data': {
      id: '/trust-center/privacy-and-data'
      path: '/trust-center/privacy-and-data'
      fullPath: '/trust-center/privacy-and-data'
      preLoaderRoute: typeof TrustCenterPrivacyAndDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center/rbi-compliance': {
      id: '/trust-center/rbi-compliance'
      path: '/trust-center/rbi-compliance'
      fullPath: '/trust-center/rbi-compliance'
      preLoaderRoute: typeof TrustCenterRbiComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center/security': {
      id: '/trust-center/security'
      path: '/trust-center/security'
      fullPath: '/trust-center/security'
      preLoaderRoute: typeof TrustCenterSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center/snv-trust-score': {
      id: '/trust-center/snv-trust-score'
      path: '/trust-center/snv-trust-score'
      fullPath: '/trust-center/snv-trust-score'
      preLoaderRoute: typeof TrustCenterSnvTrustScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/app/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/agents': {
      id: '/app/admin/agents'
      path: '/app/admin/agents'
      fullPath: '/app/admin/agents'
      preLoaderRoute: typeof AppAdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/app/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/borrowers': {
      id: '/app/admin/borrowers'
      path: '/app/admin/borrowers'
      fullPath: '/app/admin/borrowers'
      preLoaderRoute: typeof AppAdminBorrowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/cms': {
      id: '/app/admin/cms'
      path: '/app/admin/cms'
      fullPath: '/app/admin/cms'
      preLoaderRoute: typeof AppAdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/consent': {
      id: '/app/admin/consent'
      path: '/app/admin/consent'
      fullPath: '/app/admin/consent'
      preLoaderRoute: typeof AppAdminConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/fraud': {
      id: '/app/admin/fraud'
      path: '/app/admin/fraud'
      fullPath: '/app/admin/fraud'
      preLoaderRoute: typeof AppAdminFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/lenders': {
      id: '/app/admin/lenders'
      path: '/app/admin/lenders'
      fullPath: '/app/admin/lenders'
      preLoaderRoute: typeof AppAdminLendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/loans': {
      id: '/app/admin/loans'
      path: '/app/admin/loans'
      fullPath: '/app/admin/loans'
      preLoaderRoute: typeof AppAdminLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/app/admin/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/app/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/app/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/trust-score': {
      id: '/app/admin/trust-score'
      path: '/app/admin/trust-score'
      fullPath: '/app/admin/trust-score'
      preLoaderRoute: typeof AppAdminTrustScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/': {
      id: '/app/agent/'
      path: '/app/agent'
      fullPath: '/app/agent/'
      preLoaderRoute: typeof AppAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/analytics': {
      id: '/app/agent/analytics'
      path: '/app/agent/analytics'
      fullPath: '/app/agent/analytics'
      preLoaderRoute: typeof AppAgentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/commissions': {
      id: '/app/agent/commissions'
      path: '/app/agent/commissions'
      fullPath: '/app/agent/commissions'
      preLoaderRoute: typeof AppAgentCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/files': {
      id: '/app/agent/files'
      path: '/app/agent/files'
      fullPath: '/app/agent/files'
      preLoaderRoute: typeof AppAgentFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/leads': {
      id: '/app/agent/leads'
      path: '/app/agent/leads'
      fullPath: '/app/agent/leads'
      preLoaderRoute: typeof AppAgentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/notifications': {
      id: '/app/agent/notifications'
      path: '/app/agent/notifications'
      fullPath: '/app/agent/notifications'
      preLoaderRoute: typeof AppAgentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/profile': {
      id: '/app/agent/profile'
      path: '/app/agent/profile'
      fullPath: '/app/agent/profile'
      preLoaderRoute: typeof AppAgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/resources': {
      id: '/app/agent/resources'
      path: '/app/agent/resources'
      fullPath: '/app/agent/resources'
      preLoaderRoute: typeof AppAgentResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/start': {
      id: '/app/agent/start'
      path: '/app/agent/start'
      fullPath: '/app/agent/start'
      preLoaderRoute: typeof AppAgentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/support': {
      id: '/app/agent/support'
      path: '/app/agent/support'
      fullPath: '/app/agent/support'
      preLoaderRoute: typeof AppAgentSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent/training': {
      id: '/app/agent/training'
      path: '/app/agent/training'
      fullPath: '/app/agent/training'
      preLoaderRoute: typeof AppAgentTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/': {
      id: '/app/borrower/'
      path: '/app/borrower'
      fullPath: '/app/borrower/'
      preLoaderRoute: typeof AppBorrowerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/agents': {
      id: '/app/borrower/agents'
      path: '/app/borrower/agents'
      fullPath: '/app/borrower/agents'
      preLoaderRoute: typeof AppBorrowerAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/application': {
      id: '/app/borrower/application'
      path: '/app/borrower/application'
      fullPath: '/app/borrower/application'
      preLoaderRoute: typeof AppBorrowerApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/applications': {
      id: '/app/borrower/applications'
      path: '/app/borrower/applications'
      fullPath: '/app/borrower/applications'
      preLoaderRoute: typeof AppBorrowerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/apply': {
      id: '/app/borrower/apply'
      path: '/app/borrower/apply'
      fullPath: '/app/borrower/apply'
      preLoaderRoute: typeof AppBorrowerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/documents': {
      id: '/app/borrower/documents'
      path: '/app/borrower/documents'
      fullPath: '/app/borrower/documents'
      preLoaderRoute: typeof AppBorrowerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/loans': {
      id: '/app/borrower/loans'
      path: '/app/borrower/loans'
      fullPath: '/app/borrower/loans'
      preLoaderRoute: typeof AppBorrowerLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/messages': {
      id: '/app/borrower/messages'
      path: '/app/borrower/messages'
      fullPath: '/app/borrower/messages'
      preLoaderRoute: typeof AppBorrowerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/notifications': {
      id: '/app/borrower/notifications'
      path: '/app/borrower/notifications'
      fullPath: '/app/borrower/notifications'
      preLoaderRoute: typeof AppBorrowerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/offers': {
      id: '/app/borrower/offers'
      path: '/app/borrower/offers'
      fullPath: '/app/borrower/offers'
      preLoaderRoute: typeof AppBorrowerOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/payments': {
      id: '/app/borrower/payments'
      path: '/app/borrower/payments'
      fullPath: '/app/borrower/payments'
      preLoaderRoute: typeof AppBorrowerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/profile': {
      id: '/app/borrower/profile'
      path: '/app/borrower/profile'
      fullPath: '/app/borrower/profile'
      preLoaderRoute: typeof AppBorrowerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/scores': {
      id: '/app/borrower/scores'
      path: '/app/borrower/scores'
      fullPath: '/app/borrower/scores'
      preLoaderRoute: typeof AppBorrowerScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/borrower/support': {
      id: '/app/borrower/support'
      path: '/app/borrower/support'
      fullPath: '/app/borrower/support'
      preLoaderRoute: typeof AppBorrowerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/': {
      id: '/app/lender/'
      path: '/app/lender'
      fullPath: '/app/lender/'
      preLoaderRoute: typeof AppLenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/api-status': {
      id: '/app/lender/api-status'
      path: '/app/lender/api-status'
      fullPath: '/app/lender/api-status'
      preLoaderRoute: typeof AppLenderApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/audit': {
      id: '/app/lender/audit'
      path: '/app/lender/audit'
      fullPath: '/app/lender/audit'
      preLoaderRoute: typeof AppLenderAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/billing': {
      id: '/app/lender/billing'
      path: '/app/lender/billing'
      fullPath: '/app/lender/billing'
      preLoaderRoute: typeof AppLenderBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/portfolio': {
      id: '/app/lender/portfolio'
      path: '/app/lender/portfolio'
      fullPath: '/app/lender/portfolio'
      preLoaderRoute: typeof AppLenderPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/reviews': {
      id: '/app/lender/reviews'
      path: '/app/lender/reviews'
      fullPath: '/app/lender/reviews'
      preLoaderRoute: typeof AppLenderReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/risk': {
      id: '/app/lender/risk'
      path: '/app/lender/risk'
      fullPath: '/app/lender/risk'
      preLoaderRoute: typeof AppLenderRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/settings': {
      id: '/app/lender/settings'
      path: '/app/lender/settings'
      fullPath: '/app/lender/settings'
      preLoaderRoute: typeof AppLenderSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/team': {
      id: '/app/lender/team'
      path: '/app/lender/team'
      fullPath: '/app/lender/team'
      preLoaderRoute: typeof AppLenderTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lender/workbench': {
      id: '/app/lender/workbench'
      path: '/app/lender/workbench'
      fullPath: '/app/lender/workbench'
      preLoaderRoute: typeof AppLenderWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountAggregatorRoute: AccountAggregatorRoute,
  AssistanceChoiceRoute: AssistanceChoiceRoute,
  CareersRoute: CareersRoute,
  CompareOffersRoute: CompareOffersRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DigitalLendingDisclosuresRoute: DigitalLendingDisclosuresRoute,
  EmiCalculatorRoute: EmiCalculatorRoute,
  FaqRoute: FaqRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForBorrowersRoute: ForBorrowersRoute,
  ForLendersRoute: ForLendersRoute,
  GrievanceRedressalRoute: GrievanceRedressalRoute,
  HelpCenterRoute: HelpCenterRoute,
  HowItWorksRoute: HowItWorksRoute,
  KeyFactStatementRoute: KeyFactStatementRoute,
  McpRoute: McpRoute,
  MotionRoute: MotionRoute,
  PartnerEnquiryRoute: PartnerEnquiryRoute,
  PressRoute: PressRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemStatusRoute: SystemStatusRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors410Route: Errors410Route,
  Errors429Route: Errors429Route,
  Errors500Route: Errors500Route,
  Errors503Route: Errors503Route,
  ErrorsDeactivatedRoute: ErrorsDeactivatedRoute,
  ErrorsMaintenanceRoute: ErrorsMaintenanceRoute,
  ErrorsNoResultsRoute: ErrorsNoResultsRoute,
  ErrorsOfflineRoute: ErrorsOfflineRoute,
  ErrorsScriptFailureRoute: ErrorsScriptFailureRoute,
  ErrorsSecurityRoute: ErrorsSecurityRoute,
  ErrorsSuspendedRoute: ErrorsSuspendedRoute,
  ErrorsUnsupportedBrowserRoute: ErrorsUnsupportedBrowserRoute,
  LoansBusinessRoute: LoansBusinessRoute,
  LoansHomeRoute: LoansHomeRoute,
  LoansMortgageRoute: LoansMortgageRoute,
  LoansPersonalRoute: LoansPersonalRoute,
  LoansSachetRoute: LoansSachetRoute,
  PrototypeMotionRoute: PrototypeMotionRoute,
  TrustCenterPrivacyAndDataRoute: TrustCenterPrivacyAndDataRoute,
  TrustCenterRbiComplianceRoute: TrustCenterRbiComplianceRoute,
  TrustCenterSecurityRoute: TrustCenterSecurityRoute,
  TrustCenterSnvTrustScoreRoute: TrustCenterSnvTrustScoreRoute,
  BlogIndexRoute: BlogIndexRoute,
  ErrorsIndexRoute: ErrorsIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
  PrototypeIndexRoute: PrototypeIndexRoute,
  TrustCenterIndexRoute: TrustCenterIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AppAdminAgentsRoute: AppAdminAgentsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBorrowersRoute: AppAdminBorrowersRoute,
  AppAdminCmsRoute: AppAdminCmsRoute,
  AppAdminConsentRoute: AppAdminConsentRoute,
  AppAdminFraudRoute: AppAdminFraudRoute,
  AppAdminLendersRoute: AppAdminLendersRoute,
  AppAdminLoansRoute: AppAdminLoansRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminTrustScoreRoute: AppAdminTrustScoreRoute,
  AppAgentAnalyticsRoute: AppAgentAnalyticsRoute,
  AppAgentCommissionsRoute: AppAgentCommissionsRoute,
  AppAgentFilesRoute: AppAgentFilesRoute,
  AppAgentLeadsRoute: AppAgentLeadsRoute,
  AppAgentNotificationsRoute: AppAgentNotificationsRoute,
  AppAgentProfileRoute: AppAgentProfileRoute,
  AppAgentResourcesRoute: AppAgentResourcesRoute,
  AppAgentStartRoute: AppAgentStartRoute,
  AppAgentSupportRoute: AppAgentSupportRoute,
  AppAgentTrainingRoute: AppAgentTrainingRoute,
  AppBorrowerAgentsRoute: AppBorrowerAgentsRoute,
  AppBorrowerApplicationRoute: AppBorrowerApplicationRoute,
  AppBorrowerApplicationsRoute: AppBorrowerApplicationsRoute,
  AppBorrowerApplyRoute: AppBorrowerApplyRoute,
  AppBorrowerDocumentsRoute: AppBorrowerDocumentsRoute,
  AppBorrowerLoansRoute: AppBorrowerLoansRoute,
  AppBorrowerMessagesRoute: AppBorrowerMessagesRoute,
  AppBorrowerNotificationsRoute: AppBorrowerNotificationsRoute,
  AppBorrowerOffersRoute: AppBorrowerOffersRoute,
  AppBorrowerPaymentsRoute: AppBorrowerPaymentsRoute,
  AppBorrowerProfileRoute: AppBorrowerProfileRoute,
  AppBorrowerScoresRoute: AppBorrowerScoresRoute,
  AppBorrowerSupportRoute: AppBorrowerSupportRoute,
  AppLenderApiStatusRoute: AppLenderApiStatusRoute,
  AppLenderAuditRoute: AppLenderAuditRoute,
  AppLenderBillingRoute: AppLenderBillingRoute,
  AppLenderPortfolioRoute: AppLenderPortfolioRoute,
  AppLenderReviewsRoute: AppLenderReviewsRoute,
  AppLenderRiskRoute: AppLenderRiskRoute,
  AppLenderSettingsRoute: AppLenderSettingsRoute,
  AppLenderTeamRoute: AppLenderTeamRoute,
  AppLenderWorkbenchRoute: AppLenderWorkbenchRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAgentIndexRoute: AppAgentIndexRoute,
  AppBorrowerIndexRoute: AppBorrowerIndexRoute,
  AppLenderIndexRoute: AppLenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
